version: "3"
services:
  mysqldb:
    image: mysql:latest
    ports:
      - "3306:3306"
    deploy:
      labels:
        public: "true"
    environment:
        MYSQL_DATABASE: blog
        MYSQL_USER: mysql
        MYSQL_PASSWORD: mysql
        MYSQL_ROOT_PASSWORD: mysql
  wildfly:
    image: gapostolov/java-ee-blog
    environment:
      - "MYSQL_URI=mysqldb:3306"
      - "MYSQL_DATABASE=blog"
      - "MYSQL_USER=mysql"
      - "MYSQL_PASSWORD=mysql"
    ports:
      - 80:8080
    depends_on:
      - mysqldb
