---
# tasks file for apt

- name: Ensure language pack is installed
  apt: name={{ apt_lang_pack }} state=present
       update_cache={{ apt_update_cache }}

- name: Ensure essential packages are installed
  apt: name={{ item }} state=present
       update_cache={{ apt_update_cache }}
  with_items: "{{ apt_packages }}"
  when: apt_packages is defined
